version: '3.8'

services:
  db:
    image: postgres:15
    container_name: aurumwatch_db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: Hundiba123
      POSTGRES_DB: aurumwatch
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    image: redis:7
    container_name: aurumwatch_redis
    ports:
      - "6379:6379"

volumes:
  postgres_data:
